### PR TITLE
Modernized, improved bit flip, add const where appropriate, replaced union with reinterp…

### PR DESCRIPTION
**Pull request by brucewedding**
…ret cast, added missing includes, used ranges where appropriate. Must be compiled with C++ 20

### CODE REVIEW

**Comment by brucewedding** [comment]
All good

**Review by brucewedding — COMMENTED** [review]
All good

**Comment by Fudmottin** [comment]
Thanks, Bruce!

**Comment by Fudmottin** [comment]
Found about all of this on twitter first! LOL. I sure hope Yahoo doesn’t go out of business anytime soon.

**Pull request merged**
